name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

# optional 
#   env:
#      PORT:
#      ROOTPASSWORD:

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Go 
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      - name: Build
        run: scripts/buildprod.sh 
