name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

# optional 
#   env:
#      PORT:
#      ROOTPASSWORD:

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Go 
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      - name: Build
        run: scripts/buildprod.sh 

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Use gCloud CLI
        run: gcloud info

      - name: Build Docker Container
        run: gcloud builds submit --tag europe-north2-docker.pkg.dev/notely-bootdev-453411/notely-ar-repo/notely:latest .
